// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'agents', uri: Uri.parse('agents'), routeBuilder: b0Builder),
  RouteEntity(key: 'role', uri: Uri.parse('role'), routeBuilder: b1Builder),
  RouteEntity(
    key: 'select_language',
    uri: Uri.parse('select_language'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(key: 'splash', uri: Uri.parse('splash'), routeBuilder: b3Builder),
];

const routePaths = (
  path: '/',
  agents: '/agents',
  role: '/role',
  selectLanguage: '/select_language',
  splash: '/splash',
);
